version: "3"

networks:
  masters:
    external: true

services:
  
#  outer-nginx:
#    container_name: outer-nginx
#    restart: unless-stopped
#    build:
#      context: .
#      dockerfile: ./nginx-test.Dockerfile
#    environment:
#      TZ: "Europe/Moscow"
#    volumes:
#      - /home/egop/certificate:/etc/nginx/certificates
#    ports:
#      - "80:80"
#      - "443:443"
#    networks:
#      - akiana
  
  nginx:
    image: nginx-proxy
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - masters

  seq:
    image: datalust/seq
    container_name: seq
    ports:
      - "50505:80"
    volumes:
      - /home/actions/masters/seq:/data
    environment:
      ACCEPT_EULA: "Y"
      SEQ_API_CANONICALURI: "https://birdegop.ru:50505"
    networks: 
      - masters
  
  prometheus:
    image: prometheus-custom
    build:
      context: .
      dockerfile: Prometheus.Dockerfile
    container_name: prometheus
    user: root
    volumes:
      - /home/actions/masters/prometheus:/prometheus
#      - /home/actions/masters/prometheus.yml:/etc/prometheus/prometheus.yml
#      - /home/actions/masters/prometheus.web.yml:/etc/prometheus/prometheus.web.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/data'
      - '--web.config.file=/etc/prometheus/prometheus.web.yml'
    ports:
      - "55055:9090"
    networks:
      - masters
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: root
    volumes:
      - /home/actions/masters/grafana:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: http://localhost:3000
    ports:
      - "50555:3000"
    depends_on:
      - prometheus
    networks:
      - masters